apiVersion: v1
kind: Service
metadata:
  name: ai-insights-service
  namespace: finwisex
spec:
  selector:
    app: ai-insights
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3004
  type: LoadBalancer