apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: finwisex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: finwisex-auth:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/finwisex"
        - name: JWT_SECRET
          value: "your_super_secret_key_123"