apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: finwisex
spec:
  selector:
    app: finance
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: LoadBalancer