apiVersion: v1
kind: Service
metadata:
  name: investment-service
  namespace: finwisex
spec:
  selector:
    app: investment
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: LoadBalancer